name: Run BAT tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Install BAT CLI
      run: curl -o- 'https://s3.amazonaws.com/bat-wrapper/install.sh' | bash
    - name: Test with BAT
      run: bat
